const guitars = [
  {
    id: 1,
    producer: "Fame",
    title: "Fame Bonita Pino",
    category: "guitars",
    type: "Classical",
    price: 150,
    liked: "65",
    image:
      "https://images.musicstore.de/images/0960/fame-bonita-pino_1_GIT0055163-000.jpg",
    description:
      "The Fame Bonita Pino is the optimal basis for successful guitar learning because, in addition to very obliging playability, the 4/4 concert guitar convinces with a powerful and defined sound, which already unfolds with light strokes. Furthermore, the adjusted saddle and the finely notched bone nut ensure a clean intonation in all 19 frets, while the tuners allow precise tuning of the 6 nylon strings. Visually, the instrument is rounded off by wood bindings, an elaborate soundhole rosette and the matte varnish, which gently emphasizes the even grain of the tonewoods. ",
    features: [
      "Manufacturer: Fame Size: 4/4",
      "Cutaway: No",
      "Top: Spruce",
      "Solid Top: Yes",
      "Finish Top: Matte",
      "Bracing: Fame",
      "Classical Back & Sides: Mahogany",
      "Solid back & sides: No",
      "Finish Back & Sides: Matte",
      "Binding: Maple",
      "Neck: Mahogany",
      "Neck Profile: Round",
    ],
  },
  {
    id: 2,
    producer: "Fender",
    title: "Fender CN-140SCE (Natural)",
    category: "guitars",
    type: "Electro-Acoustic",
    price: 150,
    liked: "35",
    image:
      "https://images.musicstore.de/images/0960/fender-cn-140sce-natural-_1_GIT0050694-000.jpg",
    description:
      'The Fender CN-140SCE (Natural) is a 6-string Concert Electro-Acoustic Guitar which combines high playing comfort with full stage suitability. This Nylon Strung Guitar offers not only a Mahogany neck with a comfortable "Easy-to-Play" profile and 43mm saddle width, but also a cut-away for access into the high registers of the Fingerboard.',
    features: [
      "Manufacturer: Fame Size: 4/4",
      "Cutaway: No",
      "Top: Spruce",
      "Solid Top: Yes",
      "Finish Top: Matte",
      "Bracing: Fame",
      "Classical Back & Sides: Mahogany",
      "Solid back & sides: No",
      "Finish Back & Sides: Matte",
      "Binding: Maple",
      "Neck: Mahogany",
      "Neck Profile: Round",
    ],
  },
  {
    id: 3,
    producer: "Ibanez",
    title: "Ibanez AEG7TN Nylon String",
    category: "guitars",
    type: "Classical",
    price: 150,
    liked: "63",
    image:
      "https://images.musicstore.de/images/0960/ibanez-aeg7tn-nylon-string_1_GIT0052440-000.jpg",
    description:
      "With the new Ibanez AEG7TN, the traditional Japanese manufacturer revamps its universally popular AEG series. In addition to a new coat of paint, this electroacoustic classical guitar now also comes with a purpleheart fingerboard and the new Ibanez Ibanez AEQ-2T pickup system with integrated tuner. ",
    features: [
      "Manufacturer: Fame Size: 4/4",
      "Cutaway: No",
      "Top: Spruce",
      "Solid Top: Yes",
      "Finish Top: Matte",
      "Bracing: Fame",
      "Classical Back & Sides: Mahogany",
      "Solid back & sides: No",
      "Finish Back & Sides: Matte",
      "Binding: Maple",
      "Neck: Mahogany",
      "Neck Profile: Round",
    ],
  },
  {
    id: 4,
    producer: "Yamaha",
    title: "Yamaha CG 122 MC NT Cedar Natural",
    category: "guitars",
    type: "Classical",
    price: 150,
    liked: "646",
    image:
      "https://images.musicstore.de/images/0960/yamaha-cg-122-mc-nt-cedar-natural_1_GIT0018381-000.jpg",
    description:
      "The CG 122 is Yamaha 's semi-massive instrument from the affordable CG classical guitar series , which includes high-quality materials and a very expressive sound. Due to its lightweight construction , consisting of a solid cedar top and a Nato body , the Yamaha CG 122 MC NT develops a very powerful dynamic even at the slightest touch and a very strong tone, which is particularly pronounced in the bass and mid-range frequencies.",
    features: [
      "Manufacturer: Fame Size: 4/4",
      "Cutaway: No",
      "Top: Spruce",
      "Solid Top: Yes",
      "Finish Top: Matte",
      "Bracing: Fame",
      "Classical Back & Sides: Mahogany",
      "Solid back & sides: No",
      "Finish Back & Sides: Matte",
      "Binding: Maple",
      "Neck: Mahogany",
      "Neck Profile: Round",
    ],
  },
  {
    id: 5,
    producer: "Yamaha",
    title: "Yamaha C40 Classical Guitar",
    category: "guitars",
    type: "Classical",
    price: 150,
    liked: "735",
    image:
      "https://images.musicstore.de/images/0960/yamaha-c40-classical-guitar-_1_GIT0000636-000.jpg",
    description:
      "For decades, the  Yamaha C 40 series  has been the perfect basis for learning to play the guitar easily and successfully. In addition to its outstanding quality, the  Yamaha C 40 NT II 4/4 classical guitar  convinces with its perfectly adapted workmanship, which is particularly noticeable when you hold it. Despite the  laminated construction , the instrument produces a powerful sound that is interspersed with warm bass frequencies and, thanks to its  light weight , unfolds quickly and persistently.",
    features: [
      "Manufacturer: Fame Size: 4/4",
      "Cutaway: No",
      "Top: Spruce",
      "Solid Top: Yes",
      "Finish Top: Matte",
      "Bracing: Fame",
      "Classical Back & Sides: Mahogany",
      "Solid back & sides: No",
      "Finish Back & Sides: Matte",
      "Binding: Maple",
      "Neck: Mahogany",
      "Neck Profile: Round",
    ],
  },
  {
    id: 6,
    producer: "Almeria",
    title: "Almeria CG-390 Black",
    category: "guitars",
    type: "Classical",
    price: 150,
    liked: "888",
    image:
      "https://images.musicstore.de/images/0960/almeria-cg-390-black_1_GIT0046624-000.jpg",
    description:
      "The Almeria CG-390 Black is the best proof that there are decent sounding instruments for little money! But how can you offer a guitar so affordable? We buy this guitar by container bulk purchase in China directly from the factory and without wholesale or intermediate distribution. And we are happy that we can offer our customers so much guitar for so little money thanks to our high sales figures.",
    features: [
      "Manufacturer: Fame Size: 4/4",
      "Cutaway: No",
      "Top: Spruce",
      "Solid Top: Yes",
      "Finish Top: Matte",
      "Bracing: Fame",
      "Classical Back & Sides: Mahogany",
      "Solid back & sides: No",
      "Finish Back & Sides: Matte",
      "Binding: Maple",
      "Neck: Mahogany",
      "Neck Profile: Round",
    ],
  },
  {
    id: 7,
    producer: "Fame",
    title: "Fame Gig-Bag Basic",
    category: "guitars",
    type: "Classical",
    price: 50,
    liked: "457",
    image:
      "https://images.musicstore.de/images/0960/fame-gig-bag-basic-classical-guitar-_1_GIT0022882-000.jpg",
    description:
      "The Fame Gig-Bag Basic (Classical Guitar) offers protection for your acoustic guitar at a great price. The Fame Basic Classical Guitar Gig Bag features 10mm padding and a water repellent, tear resistant nylon exterior keeping your instrument out of harms reach. Also included are strong surround zips, robustly sewn straps and carry handles, plus a spacious front compartment for additional gear.",
    features: [
      "Manufacturer: Fame Size: 4/4",
      "Cutaway: No",
      "Top: Spruce",
      "Solid Top: Yes",
      "Finish Top: Matte",
      "Bracing: Fame",
      "Classical Back & Sides: Mahogany",
      "Solid back & sides: No",
      "Finish Back & Sides: Matte",
      "Binding: Maple",
      "Neck: Mahogany",
      "Neck Profile: Round",
    ],
  },
  {
    id: 8,
    producer: "Fame",
    title: "Fame Forum IV Modern ",
    category: "guitars",
    type: "Electric",
    price: 800,
    liked: "332",
    image:
      "https://images.musicstore.de/images/0960/fame-forum-iv-modern-satin-black-_1_GIT0043605-000.jpg",
    description:
      'The Fame Forum IV Modern (Satin Black) is a versatile 6-string Electric Guitar with contemporary equipment and a high playing comfort. The slender Mahogany body with Maple top offers a comfortable playing position, while the generous cut-away offers unhindered access over the entire neck. This is made of Mahogany and traditionally glued, whilst the flat "D" profile lies comfortably in the hand, the Ebony fingerboard more than suitable for advanced techniques.',
    features: [
      "Manufacturer: Fame Size: 4/4",
      "Cutaway: No",
      "Top: Spruce",
      "Solid Top: Yes",
      "Finish Top: Matte",
      "Bracing: Fame",
      "Classical Back & Sides: Mahogany",
      "Solid back & sides: No",
      "Finish Back & Sides: Matte",
      "Binding: Maple",
      "Neck: Mahogany",
      "Neck Profile: Round",
    ],
  },
  {
    id: 9,
    producer: "Fame",
    title: "Fame SE Series ST Worn Out MN Blonde",
    category: "guitars",
    type: "Electric",
    price: 300,
    liked: "231",
    image:
      "https://images.musicstore.de/images/0960/fame-se-series-st-worn-out-mn-blonde_1_GIT0051111-000.jpg",
    description:
      "With the incomparable charm of an instrument played for decades on stages and in the studio, the Fame SE Series Worn Out MN Blonde offers the look, sound and feel of a classic Relic guitar. The electric guitar in the traditional ST design relies on tried and tested ingredients in the form of an alder body with a bolt-on maple neck, whose balanced C-profile gives the tried and tested playing feel in all registers.",
    features: [
      "Manufacturer: Fame Size: 4/4",
      "Cutaway: No",
      "Top: Spruce",
      "Solid Top: Yes",
      "Finish Top: Matte",
      "Bracing: Fame",
      "Classical Back & Sides: Mahogany",
      "Solid back & sides: No",
      "Finish Back & Sides: Matte",
      "Binding: Maple",
      "Neck: Mahogany",
      "Neck Profile: Round",
    ],
  },
  {
    id: 10,
    producer: "Jackson",
    title: "Jackson JS22 Dinky DKA Satin Black",
    category: "guitars",
    type: "Electric",
    price: 150,
    liked: "12",
    image:
      "https://images.musicstore.de/images/0960/jackson-js22-dinky-dka-satin-black_1_GIT0048663-000.jpg",
    description:
      'The Dinky Arch Jackson JS Series Top JS22 DK Satin Black A convinces as an affordable Metal guitar with first-class equipment for beginners and advanced players. The electric guitar has a mahogany body in a trendy Natural Oil finish and a screwed maple neck with graphite inlays, which with its " Speed Neck " profile and compound radius fingerboard offers the perfect basis for fast riffs and endless solos.',
    features: [
      "Manufacturer: Fame Size: 4/4",
      "Cutaway: No",
      "Top: Spruce",
      "Solid Top: Yes",
      "Finish Top: Matte",
      "Bracing: Fame",
      "Classical Back & Sides: Mahogany",
      "Solid back & sides: No",
      "Finish Back & Sides: Matte",
      "Binding: Maple",
      "Neck: Mahogany",
      "Neck Profile: Round",
    ],
  },
];

module.exports = guitars;
